apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: spring-boot-metrics
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: true
    editable: true

  - name: InfluxDB-Logs
    type: influxdb
    access: proxy
    database: telegraf
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: false
    editable: true

