server.port: 8001

# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    name: ${spring.application.name}

management:
  metrics:
    tags:
      service: ${spring.application.name} # Additional, custom tag to allow filtering by service (instance)
    export:
      influx:
        auto-create-db: true
        db: spring-boot-metrics
        uri: http://localhost:8086
        step: 20s
        user-name: admin
        password: admin
  endpoints:
    web:
      exposure:
        include:
        - "*"

spring:
  application:
    name: ServiceA
  sleuth:
    # Tracing configuations:
    # Sampler probability should be between 0.0 and 1.0. 
    # 0.1 is the default, meaning that 10% of requests are 
    # actually traced. The rest is not for performance reasons.
    sampler:
      probability: 1.0

