
version: '3.1'
services:
  # Influx DB database service
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    # volumes:
    #   - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  # Chronograf (Influx UI) service
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    # volumes:
    #   - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin

  # Grafana service
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      #- ./grafana/storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    ports:
      - "6514:514/tcp"
      - "6514:514/udp"
    volumes:
      - ./rsyslog/config:/config
      - ./rsyslog/log:/logs
    depends_on:
      - influxdb
      - telegraf
    restart: always
  
  telegraf:
    image: telegraf:latest
    ports:
      - "7777:7777/tcp"
    volumes:
      # - ./rsyslog/rsyslog.conf:/etc/rsyslog.conf # uncomment if you want to configure rsyslog inside the container with a file outside of the container.
      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    restart: always

# Use these volumes and uncomment the volumes above,
# if you want data to persist beyond the shutdown and 
# restart of the services.
# volumes:
#   influxdb-storage:
#   chronograf-storage:
#   grafana-storage: