# Use postgres/example user/password credentials
version: '3.1'
services:
  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    ports:
      - 9090:9090
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
