server.port: 8003


# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    name: ${spring.application.name}

management:
  metrics:
    export:
      influx:
        auto-create-db: true
        db: spring-boot-metrics
        uri: http://localhost:8086
        step: 20s
        user-name: admin
        password: admin
  endpoints:
    web:
      exposure:
        include:
        - "*"

spring:
  application:
    name: ServiceC
  cloud:
    # Tracing configuations:
    # Sampler probability should be between 0.0 and 1.0. 
    # 0.1 is the default, meaning that 10% of requests are 
    # actually traced. The rest is not for performance reasons.
    sleuth:
      sampler:
        probability: 1.0
